var globalElements = ["accesskey",
	"class",
	"contenteditable",
	"contextmenu",
	"dir",
	"draggable",
	"dropzone",
	"hidden",
	"id",
	"itemid",
	"itemprop",
	"itemref",
	"itemscope",
	"itemtype",
	"lang",
	"slot",
	"spellcheck",
	"style",
	"tabindex",
	"title",
	"translate"
];

var attributeElementMap = {
	"accept": ["form", "input"],
	"accept-charset": ["form"],
	"accesskey": globalElements,
	"action": ["form"],
	"align": ["applet", "caption", "col", "colgroup", "hr", "iframe", "img", "table", "tbody", "td", "tfoot", "th", "thead", "tr"],
	"alt": ["applet", "area", "img", "input"],
	"async": ["script"],
	"autocomplete": ["form", "input"],
	"autofocus": ["button", "input", "keygen", "select", "textarea"],
	"autoplay": ["audio", "video"],
	"autosave": ["input"],
	"bgcolor": ["body", "col", "colgroup", "marquee", "table", "tbody", "tfoot", "td", "th", "tr"],
	"border": ["img", "object", "table"],
	"buffered": ["audio", "video"],
	"challenge": ["keygen"],
	"charset": ["meta", "script"],
	"checked": ["command", "input"],
	"cite": ["blockquote", "del", "ins", "q"],
	"class": globalElements,
	"code": ["applet"],
	"codebase": ["applet"],
	"color": ["basefont", "font", "hr"],
	"cols": ["textarea"],
	"colspan": ["td", "th"],
	"content": ["meta"],
	"contenteditable": globalElements,
	"contextmenu": globalElements,
	"controls": ["audio", "video"],
	"coords": ["area"],
	"crossorigin": ["audio", "img", "link", "script", "video"],
	"data": ["object"],
	"data-*": globalElements,
	"datetime": ["del", "ins", "time"],
	"default": ["track"],
	"defer": ["script"],
	"dir": globalElements,
	"dirname": ["input", "textarea"],
	"disabled": ["button", "command", "fieldset", "input", "keygen", "optgroup", "option", "select", "textarea"],
	"download": ["a", "area"],
	"draggable": globalElements,
	"dropzone": globalElements,
	"enctype": ["form"],
	"for": ["label", "output"],
	"form": ["button", "fieldset", "input", "keygen", "label", "meter", "object", "output", "progress", "select", "textarea"],
	"formaction": ["input", "button"],
	"headers": ["td", "th"],
	"height": ["canvas", "embed", "iframe", "img", "input", "object", "video"],
	"hidden": globalElements,
	"high": ["meter"],
	"href": ["a", "area", "base", "link"],
	"hreflang": ["a", "area", "link"],
	"http-equiv": ["meta"],
	"icon": ["command"],
	"id": globalElements,
	"integrity": ["link", "script"],
	"ismap": ["img"],
	"itemprop": globalElements,
	"keytype": ["keygen"],
	"kind": ["track"],
	"label": ["track"],
	"lang": globalElements,
	"language": ["script"],
	"list": ["input"],
	"loop": ["audio", "bgsound", "marquee", "video"],
	"low": ["meter"],
	"manifest": ["html"],
	"max": ["input", "meter", "progress"],
	"maxlength": ["input", "textarea"],
	"minlength": ["input", "textarea"],
	"media": ["a", "area", "link", "source", "style"],
	"method": ["form"],
	"min": ["input", "meter"],
	"multiple": ["input", "select"],
	"muted": ["video"],
	"name": ["button", "form", "fieldset", "iframe", "input", "keygen", "object", "output", "select", "textarea", "map", "meta", "param"],
	"novalidate": ["form"],
	"open": ["details"],
	"optimum": ["meter"],
	"pattern": ["input"],
	"ping": ["a", "area"],
	"placeholder": ["input", "textarea"],
	"poster": ["video"],
	"preload": ["audio", "video"],
	"radiogroup": ["command"],
	"readonly": ["input", "textarea"],
	"rel": ["a", "area", "link"],
	"required": ["input", "select", "textarea"],
	"reversed": ["ol"],
	"rows": ["textarea"],
	"rowspan": ["td", "th"],
	"sandbox": ["iframe"],
	"scope": ["th"],
	"scoped": ["style"],
	"seamless": ["iframe"],
	"selected": ["option"],
	"shape": ["a", "area"],
	"size": ["input", "select"],
	"sizes": ["link", "img", "source"],
	"slot": globalElements,
	"span": ["col", "colgroup"],
	"spellcheck": globalElements,
	"src": ["audio", "embed", "iframe", "img", "input", "script", "source", "track", "video"],
	"srcdoc": ["iframe"],
	"srclang": ["track"],
	"srcset": ["img"],
	"start": ["ol"],
	"step": ["input"],
	"style": globalElements,
	"summary": ["table"],
	"tabindex": globalElements,
	"target": ["a", "area", "base", "form"],
	"title": globalElements,
	"type": ["button", "input", "command", "embed", "object", "script", "source", "style", "menu"],
	"usemap": ["img", "input", "object"],
	"value": ["button", "option", "input", "li", "meter", "progress", "param"],
	"width": ["canvas", "embed", "iframe", "img", "input", "object", "video"],
	"wrap": ["textarea"],
}

var isGlobalElement = x=>globalElements.indexOf(x) > -1;
var isValidAttribute = x=>x in attributeElementMap;
var isProperAttribute = (tag, attr)=>attributeElementMap[attr].indexOf(tag) > -1;